# Generated by Django 3.1.1 on 2021-06-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_fechas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fechas',
        ),
    ]
